### ISSUE TITLE
watermark display abnormally when there have scrollbar

### ISSUE THREAD

**Issue by sunsolve** [witcan/redmine_watermark#1]
if there have long page, watermark only display on the  view at beginning, there will have no watermark  after you scroll down.

you can fix it by change  position:absolute to position:fixed

**Comment by witcan** [comment]
Thank you very much for your feedback! I tried `position:fixed` before, but the effect could not be well integrated with redmine browsing, so I chose `position:absolute`. The latest release version still uses `position:absolute`, and this problem has been fixed.

See: https://github.com/witcan/redmine_watermark/commit/f4ae641749f71bb8b30ee5ca46b2d8694ae391cf
